### ISSUE TITLE
Error for Stopping and Starting the Application Pool

### ISSUE THREAD

**Issue by lsprado** [PowerShell/xWebAdministration#27] opened 2015-06-24 14:00 UTC
I'm trying to create the DSC script for deployment web applications.
The process is Stop the application pool, copy new files and Start the application pool
But, when I create the .mof file, return the following error

Add-NodeKeys : The key properties combination 'AppPoolLeandroPradoDSC' is duplicated for keys 'Name' of resource 'xWebAppPool' in node 'VSALM'. Please make sure key properties are unique for each resource in a node.

In attach the dsc script.

![dscerror](https://cloud.githubusercontent.com/assets/13034027/8331994/bd878532-1a61-11e5-804f-8873711e0c4f.png)

What is the best way for stop and start the application pool?

**Comment by tysonjhayes** [comment] 2015-06-24 17:05
Short of renaming the application pool I'm not sure there really is a decent approach to this. I ran into the same problem with needing to stop and start a service a while back and never could figure out a good way to get it done.

**Comment by lsprado** [comment] 2015-06-24 17:34
@tysonjhayes In my case, the customer needs before the deplyment, stopping the application pool.
I research in the web about this error, and the problem is in the .mof file

**Comment by tysonjhayes** [comment] 2015-06-24 18:42
You are correct that the problem is in the DSC code itself. The issue is that Name is a key and you can't have duplicate keys in a dictionary (ultimately what is all "compiles" [used losely here] down to) hence the error. I honestly don't have any good ideas to get around it.

**Comment by ETCIAC** [comment] 2015-09-02 16:18
I believe this is best resolved by using a script resource to start the application pool and iis site at the end of the configuration.

**Comment by TravisEz13** [comment] 2016-01-26 22:31
@tysonjhayes, @lsprado 
Does the application need to be stopped before the file copy and started after the file copy?

**Comment by lsprado** [comment] 2016-01-27 16:23
@TravisEz13 When I try to copy new files, some DLLs are in using, for this reason I need stop the AppPool before deployments

**Comment by TravisEz13** [comment] 2016-01-29 01:46
I have some ideas.  Give me a week if I don't get back to you can you ping me?

**Comment by TravisEz13** [comment] 2016-04-16 21:17
@lsprado  I think for now @tysonjhayes  idea to use a script is the best.  The solution I'm thinking of will take some design work (i.e. a long time.)

**Closed** 2016-08-19 00:44 UTC
Labels: question
