### ISSUE TITLE
Why is xWebConfigKeyValue Limited to AppSettings?

### ISSUE THREAD

**Issue by craig-martin** [PowerShell/xWebAdministration#60] opened 2015-10-23 03:47 UTC
Seems like a big restriction, wondering why this resource isn't able to act on more paths.  I would like to use it to set the authentication options for example (disable/enable anonymous).

**Comment by tysonjhayes** [comment] 2015-10-23 19:14
I'd thought I'd filed an issue on this previously but I can't find it, :+1: from me.

**Comment by tysonjhayes** [comment] 2016-06-11 20:06
Actually this is a dupe of #42 (more or less). So I'm going to close this one.

**Closed by tysonjhayes** 2016-06-11 20:06 UTC
