### ISSUE TITLE
Multiple SSL Bindings

### ISSUE THREAD

**Issue by aneillans** [PowerShell/xWebAdministration#76] opened 2015-12-22 12:32 UTC
Multiple SSL bindings applied to the same site with different certificates; only the certificate specified on the LAST applied SSL binding is actually applied - to all of the bindings.

**Comment by tysonjhayes** [comment] 2015-12-22 15:44
Could you share the config you are using for this so we can begin tracking this down?

**Comment by jwainwright** [comment] 2015-12-24 16:37
Wouldn’t that be related to your SSLFlag settings? SNI requires one(and only one) default site(SSLFLag=0) per IP bound and the rest to be set to “SSLFlag=1” on the same IP. Assuming I am understanding the issue correctly.

[Think]

Jason Wainwright
Sr. Infrastructure Engineer
ThinkFinance.com<http://www.ThinkFinance.com>
4150 International Plaza, Suite 400, Ft Worth TX 76109

Privileged and Confidential. This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain privileged and/or confidential information. If you have received this e-mail in error, please notify me immediately by a return e-mail and delete this e-mail. You are hereby notified that any dissemination, distribution or copying of this e-mail and/or any attachments thereto, is strictly prohibited.

**Comment by aneillans** [comment] 2016-01-04 13:38
Section of our config:
        xWebSite NewWebSite 
        { 
            Name   = $siteName
            Ensure = "Present"
			ApplicationPool = $appPoolName 
            BindingInfo = @(
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 80
									IPAddress = '*'
									HostName = $siteName + '.' + $Stage + 'web.dom.com'
									Protocol = 'HTTP'
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 80
									IPAddress = '*'
									HostName = $siteName + '.' + $Stage + 'web'
									Protocol = 'HTTP'
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 80
									IPAddress = '*'
									HostName = $siteName + '.' + $ServerName + '.dom.com'
									Protocol = 'HTTP'
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 80
									IPAddress = '*'
									HostName = $siteName
									Protocol = 'HTTP'
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 80
									IPAddress = '*'
									HostName = $siteName + '.dom.com'
									Protocol = 'HTTP'
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 443
									IPAddress = '*'
									HostName = $siteName + '.' + $Stage + 'web.dom.com'
									Protocol = 'HTTPS'
									CertificateThumbprint = "48E121D4FEBD64D736E606E97987599446797876"
									CertificateStoreName = "WebHosting"
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 443
									IPAddress = '*'
									HostName = $siteName + '.' + $Stage + 'web'
									Protocol = 'HTTPS'
									CertificateThumbprint = "48E121D4FEBD64D736E606E97987599446797876"
									CertificateStoreName = "WebHosting"
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 443
									IPAddress = '*'
									HostName = $siteName + '.' + $ServerName + '.dom.com'
									Protocol = 'HTTPS'
									CertificateThumbprint = "48E121D4FEBD64D736E606E97987599446797876"
									CertificateStoreName = "WebHosting"
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 443
									IPAddress = '*'
									HostName = $siteName
									Protocol = 'HTTPS'
									CertificateThumbprint = "48E121D4FEBD64D736E606E97987599446797876"
									CertificateStoreName = "WebHosting"
								});
							@(MSFT_xWebBindingInformation 
								{ 
									Port = 443
									IPAddress = '*'
									HostName = $siteName + '.dom.com'
									Protocol = 'HTTPS'
									CertificateThumbprint = "48E121D4FEBD64D736E606E97987599446797876"
									CertificateStoreName = "WebHosting"
								})
						   )							   	

            PhysicalPath = "E:\Sites\$siteName"
            State = "Started"

**Comment by RSabounds** [comment] 2016-01-04 18:24
2 recommendations:
1) make sure if you're on a forked repo, you update your fork from the parent branch.
Ensure the xWebsite module has the SSLFlags binding reference in your branch.
2) ensure you place the SSLFlags value to 1 for any secondary bindings.

Alan Bounds

**Comment by SNikalaichyk** [comment] 2016-01-05 08:58
Agree with @jwainwright and @RSabounds.
You should enable *Server Name Indication* by setting the **SSLFlags** property to **1**.

**Comment by tysonjhayes** [comment] 2016-01-05 17:42
@aneillans - are you running this on Server 2008 or 2012? While I agree with most of the thread the SSLFlags property would only be set if you are running 2012 and above.

**Comment by RSabounds** [comment] 2016-01-05 20:22
@tysonjhayes  - agreed. SNI support is only provided from 2012 forward. There is no way to implement this in 2008/r2. Thus you can use host-headers, but cannot share an IP/port with multiple certificates.

**Comment by aneillans** [comment] 2016-01-05 20:27
Confirmed; this is on 2012

**Comment by tysonjhayes** [comment] 2016-01-14 19:04
@aneillans - As your running 2012 could you try setting the SSL flags as prescribed and let us know if that solves your problem?

**Comment by tysonjhayes** [comment] 2016-02-09 06:43
Howdy - as we haven't heard anything in a while I wanted to give you a chance to chime in. If you don't get back to us I'll be closing this issue in 7 days. Thanks!

**Comment by aneillans** [comment] 2016-02-11 21:11
Hi Tyson, afraid its still an active issue, but I just havent had a chance to branch and test the SSL Flags suggestion.

**Comment by tysonjhayes** [comment] 2016-05-05 00:47
Howdy - have you had a chance to test yet? I think that will resolve your issue.

**Comment by aneillans** [comment] 2016-05-11 18:30
Hi @tysonjhayes, finally got to test this today.  Spot on - SNI resolves the issue :)

**Comment by tysonjhayes** [comment] 2016-05-11 20:09
Awesome. Thanks for letting us know. I'll go ahead and close this issue.

**Comment by regedit32** [comment] 2018-11-30 21:47
@sc-bperry thanks for resurfacing this.  Are you able to make that change in your environment and verify it resolves the issue?

**Comment by sc-bperry** [comment] 2018-11-30 22:56
Oh, I've never been much of a community contributor (out of fear, not a lack of responsibility) so I'm not even sure how to do a pull request or whatever is involved. This will be a good excuse to do it, so I'll give it a shot over the weekend if I have time. I have, however, added a Script resource with a dependency on the xWebsite resource that will update the certificate bindings and that has worked in my environment. I'll at least take a stab at a fix locally update this post if I discover anything.

**Comment by sc-bperry** [comment] 2018-12-01 00:48
I cloned the resource and tested it with my VMs using Azure DSC and it assigned the correct certificates with the correct IP addresses when I specified multiple certificate/IP bindings for a site. Would it be appropriate for me to do a pull request for this? Sorry to be such a noob!

**Comment by regedit32** [comment] 2018-12-01 04:21
That's great news and thanks for taking this on.  No worries about this being your first PR here, it will get easier each time.  For info on the contribution process, you can check out [Contributing Guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md) and [Getting Started with GitHub](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#creating-a-new-pull-request).

In addition to the fix, we'll want the PR to include a regression test; probably both unit and integration.  When fixing a bug, I usually try to figure out how I would write a failing test that would have identified that there was an issue, then add the code to fix the issue and the test should pass after that.  In this case it should be a matter of updating the existing Pester tests for this resource.

If you have any questions along the way, we're happy to help.

**Comment by sc-bperry** [comment] 2019-09-18 18:16
I finally decided to follow through with this and contribute to the project, but I see that this was very recently updated by commit [a7139f12e387df061023e2a1e05fee461cef96f8](https://github.com/PowerShell/xWebAdministration/commit/a7139f12e387df061023e2a1e05fee461cef96f8) in the 2.7.0.0 dev branch. Thanks to @mcbobke for this!

**Comment by mbobke** [comment] 2019-09-18 19:28
Happy to help!

**Comment by mcbobke** [comment] 2019-09-18 19:29
Happy to help!

**Comment by mcbobke** [comment] 2019-10-02 07:21
I believe this issue can be closed.

**Comment by sc-bperry** [comment] 2019-10-02 12:44
I agree that this issue can be closed.

**Comment by regedit32** [comment] 2019-10-02 14:18
fixed by #437

**Closed by regedit32** 2019-10-02 14:18 UTC
Labels: bug, help wanted
